name: xtramile_movies
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  injectable: ^2.1.1
  provider: ^6.0.5
  get_it: ^7.6.4
  build_runner: 2.3.3
  freezed_annotation: ^2.4.1
  dio: ^5.3.2
  loader_overlay: ^2.2.0
  auto_route: ^7.8.4
  youtube_player_iframe: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  injectable_generator: ^2.1.5
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  auto_route_generator: ^7.0.0
  test: ^1.24.9
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
